apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpine
  namespace: default
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      name: test
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: test
    spec:
      terminationGracePeriodSeconds: 1
      containers:
        - name: test
          #image: litespeedtech/openlitespeed:1.8.2-lsphp83
          image: benhakim2010/php-ols:1.0
          imagePullPolicy: Always
          ports:
            - name: http
              protocol: TCP
              containerPort: 80
            - name: https
              protocol: TCP
              containerPort: 443
            - name: admin
              containerPort: 7080
---
kind: Service
apiVersion: v1
metadata:
  name: ols
spec:
  selector:
    name: test
  ports:
    - protocol: TCP
      port: 80
      name: http
    - protocol: TCP
      port: 443
      name: https
    - protocol: TCP
      port: 7080
      name: admin